### ISSUE TITLE
Error while including kmod-evdi DisplayLink

### ISSUE THREAD

**Issue by CheariX** [ublue-os/akmods#107]
### Describe the package

I try to add the evdi DisplayLink driver in my Containerfile:

```

COPY --from=ghcr.io/ublue-os/akmods:${AKMODS_FLAVOR}-${IMAGE_MAJOR_VERSION} /rpms/ /tmp/akmods-rpms
RUN find /tmp/akmods-rpms
RUN rpm-ostree install /tmp/akmods-rpms/kmods/kmod-evdi-*.rpm
```

However, during image building, I get the following error:

```
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides evdi-kmod-common >= 1.14.1 needed by kmod-evdi-6.6.8-200.fc39.x86_64-1.14.1-4.20231123gita943d98.fc39.x86_64 from @commandline
```

Did I made a mistake during the integration of this akmods?
Or is this a bug with the package?

### Image

All Images

**Comment by CheariX** [comment]
The solution seems to be to include the negativo repo *before* adding the module (not in `recipe.yml`):

```
ADD https://negativo17.org/repos/fedora-multimedia.repo  /etc/yum.repos.d/negativo17-fedora-multimedia.repo
```

Then, the command `rpm-ostree install /tmp/akmods-rpms/kmods/kmod-evdi-*.rpm` will also add `displaylink` and `libevdi` from that repository as dependencies of `kmod-evdi-*.rpm`

Is this the correct integration of that driver? Is there any documentation on how to correctly integrate this module?

**Comment by KyleGospo** [comment]
You have it correct, there's no documentation however I'm afraid
