### ISSUE TITLE
How to install the VirtualBox akmod ?

### ISSUE THREAD

**Issue by yodatak** [ublue-os/akmods#122]
### Describe the package

Hello i cannot find how to install it and i cannot find on the akmod repo https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/

● ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-nvidia:39 (index: 0)
                   Digest: sha256:f04201a1821488caedbc333991afa5b835f0418f8cc600966be7ee012d65ea58
                  Version: 39.20240130.0 (2024-01-31T04:03:22Z)
               BaseCommit: fc1981d154b646bdf8ec260d8d3acbf5c827689c7570418eaaabe4cce72deff3
                   Commit: b3ec67a7f59d820ac26b98224bbd0eba66363ad7ae0bbe7d93541456b481911b
                           ├─ copr:copr.fedorainfracloud.org:phracek:PyCharm (2023-08-10T15:35:19Z)
                           ├─ copr:copr.fedorainfracloud.org:ublue-os:akmods (2024-01-30T22:21:21Z)
                           ├─ fedora (2023-11-01T00:12:39Z)
                           ├─ google-chrome (2024-01-30T18:24:44Z)
                           ├─ rpmfusion-free (2023-11-04T16:49:08Z)
                           ├─ rpmfusion-nonfree (2023-11-04T17:26:32Z)
                           ├─ rpmfusion-nonfree-nvidia-driver (2024-01-25T09:11:40Z)
                           ├─ rpmfusion-nonfree-steam (2023-08-10T16:27:35Z)
                           └─ updates (2024-02-01T01:46:41Z)
                   Staged: no
                StateRoot: fedora
      RemovedBasePackages: gst-editing-services 1.22.5-1.fc39 rygel 0.42.5-1.fc39
          LayeredPackages: fish flatpak-spawn langpacks-fr openssl1.1 perf strace vagrant
            LocalPackages: xpipe-1.7.16-1.x86_64

### Image

Silverblue

**Comment by HikariKnight** [comment]
you need to make a custom image, akmods have to be included with the image to function.

see [Usage in Readme](https://github.com/ublue-os/akmods?tab=readme-ov-file#usage)
if you do not know how to make your own image, check out https://github.com/ublue-os/image-template or https://blue-build.org if you have no idea how to work with container files and want it as abstracted as possible.
