### ISSUE TITLE
Update xone from upstream

### ISSUE THREAD

**Issue by rumble19** [ublue-os/akmods#136]
### Describe the package

Please merge upstream fixes released recently from https://github.com/medusalix/xone or specifically [this commit](https://github.com/medusalix/xone/commit/05b7a2aa2eb416ebc031c5ec81fdb593e18fbd95) to fix an issue with the wireless xbox 2.4ghz dongles locking up. 

Issue referenced in discord here: https://discord.com/channels/1072614816579063828/1211498927489159168

Thanks!

### Image

Bazzite

**Comment by KyleGospo** [comment]
https://github.com/ublue-os/packages/commit/19cde99bae93af2b7f57fa4c07a87537f6e1f0df
