### ISSUE TITLE
Fedora 40 Builds

### ISSUE THREAD

**Issue by p5** [ublue-os/akmods#144]
@bsherman has enabled builds for Fedora 40 but disabled those which are not yet supported or fail to compile.

This issue will track the rollout to the remaining packages.

Builds to enable: 
- [x] evdi: negativo17 does not yet provide F40
- ~~ gasket: compile failure (kernel 6.8) / removed ~~ - will be added to ucore
- ~~nvidia-470xx: compile failure~~ - will not enable: rpmfusion has dropped support
- ~~ rtl18814au: compile failure (kernel 6.8) ~~ see #185 
- ~~ rtl188xxau: compile failure (kernel 6.8)~~ see #185 
- [x] https://github.com/ublue-os/akmods/pull/168 (kernel 6.8 builds on F40 but not F39, rpmfusion fix pending)
- [x] xpadneo: negativo17 does not yet provide F40

**Comment by bsherman** [comment]
Someone checked the `rtl188xxau` box... what does that mean?

**Comment by noelmiller** [comment]
> Someone checked the `rtl188xxau` box... what does that mean?

May have been me? I'm on my phone, probably an accident.

**Comment by bsherman** [comment]
> > Someone checked the `rtl188xxau` box... what does that mean?
> 
> May have been me? I'm on my phone, probably an accident.

no worries! I was just confused :grin:

**Comment by bsherman** [comment]
#154

**Comment by bsherman** [comment]
>     * [ ]  rtl18814au: compile failure (kernel 6.8)
>     * [ ]  rtl188xxau: compile failure (kernel 6.8)

These 2 images still aren't building I did try rebuilds in copr and then local test builds, but no luck. Filed a ticket and won't do these for F40 #185
