### ISSUE TITLE
facetimehd kmod is not building

### ISSUE THREAD

**Issue by nobodywatchin** [ublue-os/akmods#194]
In my custom image, the facetimehd kmod fails. I have checked with the blue-build team and they think it has something to do with kernel versions.

Here is what it gives me:
`#37 0.311 ================================================= Start Akmods Module =================================================
#37 0.618 Installing akmods
#37 0.620 Installing: facetimehd
#37 0.674 Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:ublue-os:akmods fedora-multimedia copr:copr.fedorainfracloud.org:ublue-os:staging copr:copr.fedorainfracloud.org:che:nerd-fonts copr:copr.fedorainfracloud.org:kylegospo:bazzite copr:copr.fedorainfracloud.org:kylegospo:system76-scheduler copr:copr.fedorainfracloud.org:kylegospo:bazzite-multilib tailscale-stable rpmfusion-nonfree rpmfusion-nonfree-updates-testing rpmfusion-free rpmfusion-nonfree-updates rpmfusion-free-updates-testing rpmfusion-free-updates updates fedora-cisco-openh264 fedora updates-archive
#37 1.212 Updating metadata for 'copr:copr.fedorainfracloud.org:ublue-os:akmods'...done
#37 2.781 Updating metadata for 'fedora-multimedia'...done
#37 3.448 Updating metadata for 'copr:copr.fedorainfracloud.org:ublue-os:staging'...done
#37 3.775 Updating metadata for 'copr:copr.fedorainfracloud.org:che:nerd-fonts'...done
#37 3.895 Updating metadata for 'copr:copr.fedorainfracloud.org:kylegospo:bazzite'...done
#37 4.538 Updating metadata for 'copr:copr.fedorainfracloud.org:kylegospo:system76-scheduler'...done
#37 4.850 Updating metadata for 'copr:copr.fedorainfracloud.org:kylegospo:bazzite-multilib'...done
#37 5.142 Updating metadata for 'tailscale-stable'...done
#37 5.914 Updating metadata for 'rpmfusion-nonfree'...done
#37 6.705 Updating metadata for 'rpmfusion-nonfree-updates-testing'...done
#37 7.878 Updating metadata for 'rpmfusion-free'...done
#37 8.725 Updating metadata for 'rpmfusion-nonfree-updates'...done
#37 9.518 Updating metadata for 'rpmfusion-free-updates-testing'...done
#37 10.81 Updating metadata for 'rpmfusion-free-updates'...done
#37 12.23 Updating metadata for 'updates'...done
#37 12.61 Updating metadata for 'fedora-cisco-openh264'...done
#37 15.32 Updating metadata for 'fedora'...done
#37 15.94 Updating metadata for 'updates-archive'...done
#37 15.95 error: Updating rpm-md repo 'updates-archive': cannot update repo 'updates-archive': Yum repo downloading error: Downloading error(s): repodata/2e7db4492173b6c437fd1299dc335e63d09f24cbdadeac5175a61b787c2f7a44-filelists.xml.zck - Cannot download, all mirrors were already tried without success; Last error: Status code: 403 for https://fedoraproject-updates-archive.fedoraproject.org/fedora/40/x86_64/repodata/2e7db4492173b6c437fd1299dc335e63d09f24cbdadeac5175a61b787c2f7a44-filelists.xml.zck (IP: 3.161.213.74)
#37 ERROR: process "/bin/sh -c source /tmp/scripts/exports.sh   && /tmp/scripts/run_module.sh akmods '{\"type\":\"akmods\",\"install\":[\"facetimehd\"]}'" did not complete successfully: exit code: 1
------
 > [stage-5 4/5] RUN   --mount=type=bind,from=stage-config,src=/config,dst=/tmp/config,rw   --mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw   --mount=type=bind,from=stage-akmods-main,src=/rpms,dst=/tmp/rpms,rw   --mount=type=bind,from=ghcr.io/blue-build/cli:83d654d3a25c2fc679e8d814badd579ec5337020-build-scripts,src=/scripts/,dst=/tmp/scripts/   --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-myos-gnome-intel-mac-latest,sharing=locked   source /tmp/scripts/exports.sh   && /tmp/scripts/run_module.sh akmods '{"type":"akmods","install":["facetimehd"]}':
6.705 Updating metadata for 'rpmfusion-nonfree-updates-testing'...done
7.878 Updating metadata for 'rpmfusion-free'...done
8.725 Updating metadata for 'rpmfusion-nonfree-updates'...done
9.518 Updating metadata for 'rpmfusion-free-updates-testing'...done
10.81 Updating metadata for 'rpmfusion-free-updates'...done
12.23 Updating metadata for 'updates'...done
12.61 Updating metadata for 'fedora-cisco-openh264'...done
15.32 Updating metadata for 'fedora'...done
15.94 Updating metadata for 'updates-archive'...done
15.95 error: Updating rpm-md repo 'updates-archive': cannot update repo 'updates-archive': Yum repo downloading error: Downloading error(s): repodata/2e7db4492173b6c437fd1299dc335e63d09f24cbdadeac5175a61b787c2f7a44-filelists.xml.zck - Cannot download, all mirrors were already tried without success; Last error: Status code: 403 for https://fedoraproject-updates-archive.fedoraproject.org/fedora/40/x86_64/repodata/2e7db4492173b6c437fd1299dc335e63d09f24cbdadeac5175a61b787c2f7a44-filelists.xml.zck (IP: 3.161.213.74)
------
Containerfile:59
--------------------
  58 |     # Module RUNs
  59 | >>> RUN \
  60 | >>>   --mount=type=bind,from=stage-config,src=/config,dst=/tmp/config,rw \
  61 | >>>   --mount=type=bind,from=stage-modules,src=/modules,dst=/tmp/modules,rw \
  62 | >>>   --mount=type=bind,from=stage-akmods-main,src=/rpms,dst=/tmp/rpms,rw \
  63 | >>>   --mount=type=bind,from=ghcr.io/blue-build/cli:83d654d3a25c2fc679e8d814badd579ec5337020-build-scripts,src=/scripts/,dst=/tmp/scripts/ \
  64 | >>>   --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-myos-gnome-intel-mac-latest,sharing=locked \
  65 | >>>   source /tmp/scripts/exports.sh \
  66 | >>>   && /tmp/scripts/run_module.sh akmods '{"type":"akmods","install":["facetimehd"]}'
  67 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c source /tmp/scripts/exports.sh   && /tmp/scripts/run_module.sh akmods '{\"type\":\"akmods\",\"install\":[\"facetimehd\"]}'" did not complete successfully: exit code: 1
[02:07:02 ERROR] => Failed to build image
Error: Process completed with exit code 1.
`

**Comment by fiftydinar** [comment]
Did you add this COPR repo before installing facetime akmod?

https://copr.fedorainfracloud.org/coprs/mulderje/facetimehd-kmod/package/facetimehd-kmod

It's not indicated in the README that this is not in ublue-os/akmods COPR repo, so I understand why I get some error reports about Looking Glass akmod & now this one.

**Comment by nobodywatchin** [comment]
> Did you add this COPR repo before installing facetime akmod?
> 
> 
> 
> https://copr.fedorainfracloud.org/coprs/mulderje/facetimehd-kmod/package/facetimehd-kmod
> 
> 
> 
> It's not clearly indicated in the README that this is not in ublue-os/akmods COPR repo, so I understand why I get some error reports about Looking Glass akmod & now this one.

ohh okay, so I have to add the COPR repo then the akmod. thank you i will try that tonight
