### ISSUE TITLE
Build fails when trying to add akmods to image

### ISSUE THREAD

**Issue by robotictacos** [ublue-os/akmods#224]
Here is the relevant terminal output:
`0.161 ================================================ Start 'akmods' Module ================================================
0.174 Installing akmods
0.175 Installing: openrgb xpadneo
0.198 error: Handling argument /tmp/rpms/kmods/*openrgb*.rpm: No such file or directory (os error 2)`

Here is my recipe.yml:
[Recipe.yml](https://raw.githubusercontent.com/robotictacos/xps17-fedora/main/recipes/recipe.yml)

**Comment by robotictacos** [comment]
Just FYI, I have stripped out all my akmods except one, as a test, and it always fails:

  - type: akmods
    base: fsync # if not specified, classic "main" base is used by default
    install:
      - openrgb

**Comment by robotictacos** [comment]
![image](https://github.com/user-attachments/assets/79a5c6b6-50dc-4054-9e1f-b087bb238679)

Is this happening because there is no tag 'fsync-40'?

**Comment by fiftydinar** [comment]
This issue should be fixed now:
https://github.com/ublue-os/akmods/pull/232

**Comment by robotictacos** [comment]
Update:  I got it to build by modifying 
  - type: akmods
    base: fsync-40 

to this:
  - type: akmods
    base: fsync

Y'all might want to update the README on the akmods page but otherwise I'd say its good to go.
