### ISSUE TITLE
Fingerprint Drivers XPS 15 9500

### ISSUE THREAD

**Issue by juliusm254** [ublue-os/akmods#226]
### Describe the package

I'd like to request Fingerprint Drivers XPS 15 9500 to allow logging into the system with.

I am running on bluefin dx.

### Image

All Images

**Comment by bronson** [comment]
Yeah, it's unreasonable to install that on everyone's Bluefin.

Would this be a good time to [build a custom image](https://github.com/ublue-os/image-template)?

_FROM bluefin ADD libfprint-tod AND driver_
