### ISSUE TITLE
F41 akmods Tracker

### ISSUE THREAD

**Issue by bsherman** [ublue-os/akmods#248]
Tracking Status of akmods for F41 Release:

- [x] **akmods (common)**
    - [x] xpadneo
        - ~~Not yet available for F41.~~ Fixed in https://github.com/ublue-os/akmods/pull/260 
        - Workaround: build disabled, but should auto-enable when required package shows up in negativo17's repo.
- [x] **akmods-extra**
    - [x] evdi
        - Not yet available for F41.
        - Workaround: build disabled, but should auto-enable when required package shows up in negativo17's repo.
    - [x] vhba
        - ~~Not yet available for F41.~~ Fixed in: https://github.com/ublue-os/akmods/commit/5ec92fca98102c7e7d79560fb8b97d17097a661b
        - Workaround: build disabled, Watch for F41 at https://copr.fedorainfracloud.org/coprs/rok/cdemu/package/vhba-kmod/
    - [x] zenergy
        - Currently fails on kernel 6.11.1
        - Workaround: @KyleGospo has resolved. Building fine
- [x] **akmods-nvidia**
    - [x] nvidia
        - nvidia was failing due to `rpmrebuild` issues.
        - Workaround: @m2Giles has resolved. Building fine

**Comment by m2Giles** [comment]
For rpmrebuild it's gonna be something we need to add from now on it seems like. The issue is caused by rpmbuild running prep commands that can nuke the build root.

**Comment by m2Giles** [comment]
Additionally, the rpmrebuild command is used with all kmods and kernel-cache. It just showed up first with Nvidia since it only builds the one set of kmods

**Comment by bsherman** [comment]
> For akmods-extra 41. Ayn-platform rpm needs a copr rebuild. The 41 package is not the latest tarball.

I rebuilt ayn-platform in COPR and kicked off a rebuild here: https://github.com/ublue-os/akmods/actions/runs/11227926052

**Comment by coffeelover** [comment]
It seems that the xpadneo and evdi rpms are now present in negativo17's repo.

**Comment by p5** [comment]
> It seems that the xpadneo and evdi rpms are now present in negativo17's repo.

Awesome!  Have created a PR so we can get these building!

**Comment by noelmiller** [comment]
Created issue upstream with Negativo: https://github.com/negativo17/evdi-kmod/issues/2

**Comment by scaronni** [comment]
Just stumbled on this bug due to the fact that I missed building `displaylink` for Fedora 41 as I don't have a DisplayLink docking station anymore. Feel free to ping me in this sort of tracking issues.

Thanks.

**Comment by scaronni** [comment]
I usually try to have everything available for new distribution releases ~1 month before the actual relase date, this time I was a bit under pressure at work and could not dedicate so much time to it as I wanted.

**Comment by noelmiller** [comment]
@scaronni No worries! I really appreciate you being able to get this fixed so quickly! I will try running a build now.
