### ISSUE TITLE
Natec Genesis P65 (xbox360/ps3) gamepad - xbox360 mode stopped working

### ISSUE THREAD

**Issue by lorduskordus** [ublue-os/akmods#59]
## What I tried

+ Roll back to a pinned uBlue image I keep as a backup. That image is from Aug 18, 2023 and the controller **WORKS THERE**.
+ I also tried rebasing to normal, official, latest Silverblue. It also **WORKS THERE**.

## Info about the controller

+ It has xbox360 and a ps3 mode switch.
+ In the ps3 mode, it works, but that mode is unusable even on Windows.
+ In xbox360 mode, under /dev/input/by-id, it shows up as 'usb-ShanWan_Controller_XBOX_360_For_Windows..' Using cat on that file throws SIGPIPE error. This mode worked flawlessly for like 3 years until now.

## What I suspect is the issue

+ Considering normal latest Silverblue works, a pinned uBlue image from Aug 18, 2023 also works, looking around here I suspect commits from Aug 27, 2023 caused it. Those mention stuff related to xbox controllers.

**Comment by bsherman** [comment]
I'm not sure what to tell you.  My understanding is that the [`xpad-noone` driver](https://github.com/ublue-os/xpad-noone) is stock, upstream linux `xpad`... except we've commented out support for Xbox One controllers. 


The driver should support your device as it shares the device and vendor ID's: `{ 0x045e, 0x028e, "Microsoft X-Box 360 pad", 0, XTYPE_XBOX360 },`
As can be seen here: 
https://github.com/ublue-os/xpad-noone/commit/c6746b3e0a95a817550a686700eb3cdfe6b27c76#diff-3d985fe7837dec4db1df27733cece3b37633535ef91b1cbdf1c8b6eec4f692dbL154

Perhaps try manually loading the module after plugging in the controller?  `sudo modprobe xpad-noone`

@KyleGospo not sure if you have anything more to add?

**Comment by KyleGospo** [comment]
https://github.com/fwupd/fwupd/issues/828

Looks like 8bitdo had a similar issue, and it's due to how they fake their VID.

**Comment by KyleGospo** [comment]
In the meantime you can blacklist the 3 new drivers and override the xpad blacklist by making an empty copy in etc with the same name

**Comment by fiftydinar** [comment]
> In the meantime you can blacklist the 3 new drivers and override the xpad blacklist by making an empty copy in etc with the same name, returning you to stock kernel behavior.

What do you think of making just command for this?
