### ISSUE TITLE
Create build matrix to support distinct builds for kernel variants

### ISSUE THREAD

**Issue by bsherman** [ublue-os/akmods#68]
In order to support custom kernels (eg for [asus](https://github.com/ublue-os/asus) and [surface](https://github.com/ublue-os/surface) images) we need those kernels to be used as part of the kmods build process.

Perhaps we do something like this:
```
matrix:
    kernel_flavor: [default, asus, surface]
```

And then our kmods Containerfile(s):
1. use default kernel/kernel-devel packages for `default`
2. replace kernel/kernel-devel packages for `asus`/`surface`
3. build kmods with the respective kernel packages

Tags should be something like this:
- akmods:main-38
- akmods-nvidia:main-38-535
- akmods:asus-38
- akmods-nvidia:asus-38-535
- akmods:surface-38
- akmods-nvidia:surface-38-535

**Comment by KyleGospo** [comment]
Looks like some more work is needed here, while the kernels install the akmods are not built for them specifically.
https://github.com/ublue-os/surface/pull/11
https://github.com/ublue-os/asus/pull/8

**Comment by KyleGospo** [comment]
Good to close!
